#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
i=0
while [ $i -lt 13 ];
do
  echo "Hour: $i"
  (( i++ ))
  h=1
    while [ $h -lt 60 ]
    do
      echo "$h"
      (( h++ ))
    done
done
